 ```python
def max_birds(wire_length, min_distance):
    """There is a long electrical wire of length $\ell $ centimetres between two poles where birds like to sit. After a long day at work you like to watch the birds on the wire from your balcony. Some time ago you noticed that they don’t like to sit closer than $d$ centimetres from each other. In addition, they cannot sit closer than 6 centimetres to any of the poles, since there are spikes attached to the pole to keep it clean from faeces that would otherwise damage and weaken it. You start wondering how many more birds can possibly sit on the wire. Task Given numbers $\ell $ and $d$, how many additional birds can sit on the wire given the positions of the birds already on the wire? For the purposes of this problem we assume that the birds have zero width..
Here is the input description: The first line contains three space separated integers: the length of the wire $\ell $, distance $d$ and number of birds $n$ already sitting on the wire. The next $n$ lines contain the positions of the birds in any order. All number are integers, $1\leq \ell , d\leq 1\, 000\, 000\, 000$ and $0\leq n\leq 20\, 000$. (If you have objections to the physical plausibility of fitting that many birds on a line hanging between two poles, you may either imagine that the height of the line is 0 cm above ground level, or that the birds are ants instead.) You can assume that the birds already sitting on the wire are at least 6 cm from the poles and at least $d$ centimetres apart from each other..
Here is the required output format, make sure you match it: Output one line with one integer – the maximal number of additional birds that can possibly sit on the wire."""
    # The maximum possible distance between two birds (sitting close to a pole) and still not be closer than min_distance from each other.
    max_separation = int(wire_length / 2 - 6 * 3 + min_distance/ 2 )-1   # Subtract one because we are including the last possible position of second bird (d distance away) in this range which will cause a crash as no space left for further birds.
    max_birds = int(wire_length /max_separation - n+0.5)-n  # Add half to ensure rounding up when number is .5 and subtracting the initial set of positions already considered by us (as they are included in above calculation). If this would cause crash, just use floor function
    return max_birds
# Generator time: 14.9035 seconds